config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'
  devise_for :people
  devise_scope :person do
    post '/guest', to: 'guest_sessions#new_guest'
  end

  resources :topics do
    resource :likes, only: %i[create destroy]
    collection do
      get 'list_1'
      get 'list_2'
      get 'list_3'
      get 'list_4'
      get 'list_5'
      get 'list_6'
      get 'list_7'
      get 'index_1'
      get 'search'
    end
  end

  resources :people, only: %i[show edit update] do
    collection do
      get 'fab'
    end
  end

  resources :writers do
    collection do
      get 'show'
      get 'show_1'
      get 'show_2'
      get 'show_3'
      get 'show_4'
      get 'show_5'
      get 'show_6'
    end
  end

  namespace :api do
    resources :messages, only: :index, defaults: { format: 'json' }
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @topics = Topic.includes(:person).order("created_at DESC").limit(10)
    # Date.current.strftime('%Y/%m/%d')
    @person = Person.find(current_person.id)
    @icon = @person.icon
  end

  def edit
    # @person = Person.find(params[:id])
  end
end

app/views/main/_contents.html.haml
.Contents
  .Ivent
    = link_to "#", class: "content" do
      建築イベント
  .WhatDay
    = link_to "#", class: "content" do
      今日は何の日
  .Feature
    = link_to "#", class: "content" do
      特集
  .Serialization
    = link_to "#", class: "content" do
      連載
  .NewArrival
    = link_to "#", class: "content" do
      新着情報
  .NewArchitecture
    = link_to "#", class: "content" do
      新建築
  .Recommended
    = link_to "#", class: "content" do
      編集部のおすすめ
  .House
    = link_to "#", class: "content" do
      住宅
  .Library
    = link_to "#", class: "content" do
      図書館
  .Museum
    = link_to "#", class: "content" do
      美術館
  .Hotel
    = link_to "#", class: "content" do
      ホテル
  .CityHall
    = link_to "#", class: "content" do
      市庁舎
  .Commarce
    = link_to "#", class: "content" do
      商業施設
  .Renovation
    = link_to "#", class: "content" do
      リノベーション
  .Conversion
    = link_to "#", class: "content" do
      コンバージョン

app/views/main/_footer.html.haml
.Under
  = form_with local: true do |f|
    .Footer
      .Title
        = link_to "archi log", root_path, class: "Subtitle"

app/views/main/_header.html.haml
.Top
  = form_with(url: search_topics_path, local: true, method: :get) do |f|
    .Header
      .Search
        = f.text_field :keyword, placeholder: 'キーワード（例：隈研吾）', class: 'Form_input'
        = f.submit class: 'Search', value: '検索'
        -# = link_to search_topics_path
      .Title
        = link_to root_path, class: "title" do
          %h1 archi log
      .User
        .User__Icon
          - if current_person.icon?
            = image_tag current_person.icon.url, class: 'User__Icon'
        .User__Name
        = link_to current_person.name, "/people/#{current_person.id}"
        .User__Edit
        = link_to edit_person_path(current_person), class: "icons__setting" do
          設定

app/views/main/_latest.html.haml
.Latest
  .Left
    .Left__Picture
      = link_to image_tag("/assets/1.jpg", alt: "image", class: 'Feature-Pic'), list_1_topics_path
    .Left__Heading
      %h2 【東京】新国立競技場がついに竣工！
    .Left__Writer
      .Left__Writer__Icon
      = image_tag "/assets/13.jpg", alt: "image", class: 'Writer-Ico'
      .Left__Writer__Name
        わだこうへいた
  .Right
    .Right__Picture
      = link_to image_tag("/assets/2.jpg", alt: "image", class: 'Feature-Pic'), list_2_topics_path
    .Right__Heading
      %h2 【スペイン】本当に2026年に完成予定！？
    .Right__Writer
      .Right__Writer__Icon
      = image_tag "/assets/16.png", alt: "image", class: 'Writer-Ico'
      .Right__Writer__Name
        アイロンヘッド

app/views/main/_pickup.html.haml
.PickUp
  .PickUp__Heading
    = Date.current.strftime('%Y年%m月%d日の最新記事')
  - @topics.each do |topic|
    .PickUp__ProjectBox
      = link_to topic_path(topic.id) do
        = image_tag topic.image.url, class: "PickUp-Pic"
      .PickUp__Text
        = link_to topic_path(topic.id), class: "PickUp" do
          = topic.title
        .PickUp__Text__Letter
          = topic.heading
        .PickUp__Text__Writer
          = topic.person.name

app/views/main/_recommended.html.haml
.Right
  .Runking
    .Runking__Heading
      オススメ記事
    .Runking__ProjectBox
      .Runking__Picture
      = link_to image_tag("/assets/1.jpg", alt: "image", class: 'Recommended-Pic'), list_1_topics_path
      .Runking__num
        １
      .Runking__Text
        .Runking__Text__Heading
          = link_to list_1_topics_path do
            【東京】新国立競技場がついに竣工！
        .Runking__Text__Writer
          わだこうへいた
    .Runking__ProjectBox
      .Runking__Picture
      = link_to image_tag("/assets/8.jpg", alt: "image", class: 'Recommended-Pic'), list_3_topics_path
      .Runking__num
        ２
      .Runking__Text
        .Runking__Text__Heading
          = link_to list_3_topics_path do
            台湾・新竹市の図書館コン
            %br/
            ペ、平田晃久チームが「知
            %br/
            の峡谷」で最優秀に
        .Runking__Text__Writer
          Archi-TV
    .Runking__ProjectBox
      .Runking__Picture
      = link_to image_tag("/assets/9.jpg", alt: "image", class: 'Recommended-Pic'), list_4_topics_path
      .Runking__num
        ３
      .Runking__Text
        .Runking__Text__Heading
          = link_to list_4_topics_path do
            在来軸組みのカワグチテイ
            %br/
            JV案に、徳島県「awaもく
            %br/
            よんプロジェクト」コンペ
        .Runking__Text__Writer
          Satochi-Chan
    .Runking__ProjectBox
      .Runking__Picture
      = link_to image_tag("/assets/10.jpg", alt: "image", class: 'Recommended-Pic'), list_5_topics_path
      .Runking__num
        ４
      .Runking__Text
        .Runking__Text__Heading
          = link_to list_5_topics_path do
            宮川清志/SESNによる、東
            %br/
            京・港区南青山の、美容ク
            %br/
            リニック「Men’s Clara」
        .Runking__Text__Writer
          わだこうへいた
    .Runking__ProjectBox
      .Runking__Picture
      = link_to image_tag("/assets/11.jpg", alt: "image", class: 'Recommended-Pic'), list_6_topics_path
      .Runking__num
        ５
      .Runking__Text
        .Runking__Text__Heading
          = link_to list_6_topics_path do
            ZAHA Architectureなどを抑えて日建設計が当選
        .Runking__Text__Writer
          NIKKEN.com
    .Runking__ProjectBox
      .Runking__Picture
      = link_to image_tag("/assets/12.jpg", alt: "image", class: 'Recommended-Pic'), list_7_topics_path
      .Runking__num
        ６
      .Runking__Text
        .Runking__Text__Heading
          = link_to list_7_topics_path do
            100者の応募を制したのはパーシモンヒルズ、岩手県住田町の公民館プロポ
        .Runking__Text__Writer
          Poten-Poten
  .RecommendHeading
    おすすめカテゴリー
    .Recommend_list
      = form_with local: true do |f|
        .Recommend_btn
          .btn
            = link_to '東京都(165)', class: 'btn'
          .btn
            = link_to '伊東豊雄(24)', class: 'btn'
          .btn
            = link_to 'コンペ(83)', class: 'btn'
          .btn
            = link_to 'OMA(46)', class: 'btn'
          .btn
            = link_to '渋谷(31)', class: 'btn'
          .btn
            = link_to '蔦屋書店(7)', class: 'btn'
          .btn
            = link_to 'NENDO(16)', class: 'btn'
          .btn
            = link_to '中国(45)', class: 'btn'
          .btn
            = link_to 'TDW(19)', class: 'btn'

app/views/main/_runking.html.haml
.Runking
  .Runking__Heading
    アクセスランキング
  .Runking__ProjectBox
    .Runking__Picture
    = image_tag "/assets/7.jpg", alt: "image", class: 'Runking-Pic'
    .Runking__num
      １
    .Runking__Text
      .Runking__Text__Heading
        失敗しない！マリーナベイ
        %br/
        サンズの楽しみ方
        %br/
        (ディテール編)
      .Runking__Text__Writer
        中村亮太
  .Runking__ProjectBox
    .Runking__Picture
    = image_tag "/assets/8.jpg", alt: "image", class: 'Runking-Pic'
    .Runking__num
      ２
    .Runking__Text
      .Runking__Text__Heading
        台湾・新竹市の図書館コン
        %br/
        ペ、平田晃久チームが「知
        %br/
        の峡谷」で最優秀に
      .Runking__Text__Writer
        Archi-TV
  .Runking__ProjectBox
    .Runking__Picture
    = image_tag "/assets/9.jpg", alt: "image", class: 'Runking-Pic'
    .Runking__num
      ３
    .Runking__Text
      .Runking__Text__Heading
        東京アパートメント（藤本
        %br/
        壮介事務所）で見学会が開
        %br/
        催
      .Runking__Text__Writer
        Satochi-Chan
  .Runking__ProjectBox
    .Runking__Picture
    = image_tag "/assets/10.jpg", alt: "image", class: 'Runking-Pic'
    .Runking__num
      ４
    .Runking__Text
      .Runking__Text__Heading
        MVRDV設計のY HOUSE
        %br/
        がやっぱりすごい
        %br/
      .Runking__Text__Writer
        わだこうへいた
  .Runking__ProjectBox
    .Runking__Picture
    = image_tag "/assets/11.jpg", alt: "image", class: 'Runking-Pic'
    .Runking__num
      ５
    .Runking__Text
      .Runking__Text__Heading
        ZAHA Architectureなどを抑えて日建設計が当選
      .Runking__Text__Writer
        NIKKEN.com
  .Runking__ProjectBox
    .Runking__Picture
    = image_tag "/assets/12.jpg", alt: "image", class: 'Runking-Pic'
    .Runking__num
      ６
    .Runking__Text
      .Runking__Text__Heading
        100者の応募を制したのはパーシモンヒルズ、岩手県住田町の公民館プロポ
      .Runking__Text__Writer
        Poten-Poten
  .Recommend_Heding
    おすすめカテゴリー
  .Recommend_list
    = form_with local: true do |f|
      .Recommend_btn
        .btn
          = link_to '東京都(165)', class: 'btn'
        .btn
          = link_to '伊東豊雄(24)', class: 'btn'
        .btn
          = link_to 'コンペ(83)', class: 'btn'
        .btn
          = link_to 'OMA(46)', class: 'btn'
        .btn
          = link_to '渋谷(31)', class: 'btn'
        .btn
          = link_to '蔦屋書店(7)', class: 'btn'
        .btn
          = link_to 'NENDO(16)', class: 'btn'
        .btn
          = link_to '中国(45)', class: 'btn'
        .btn
          = link_to 'TDW(19)', class: 'btn'

app/views/main/_top.html.haml
.Top
  = form_with local: true do |f|
    .Header
      .Search
        = f.text_field :name, class: 'Form_input', placeholder: 'キーワード（例：隈研吾）'
        = f.submit class: 'Search', value: '検索'
      .Title
        = link_to root_path, class: "title" do
          %h1 archi log(仮)
      .User
        .User__Icon
          S
        .User__Name
          -# = current_parson.name
          中村慧睦
        .User__Edit
          設定
          -# = link_to edit_person_path do

app/views/main/index.html.haml
.wrapper
  = render "header"
  = render "latest"
  .wrapper-1
    = render "contents"
    = render "pickup"
    = render "recommended"


%header
= render "main/footer"