config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'
  devise_for :people
  devise_scope :person do
    post '/guest', to: 'guest_sessions#new_guest'
  end

  resources :topics do
    resource :likes, only: %i[create destroy]
    collection do
      get 'list_1'
      get 'list_2'
      get 'list_3'
      get 'list_4'
      get 'list_5'
      get 'list_6'
      get 'list_7'
      get 'index_1'
      get 'search'
    end
  end

  resources :people, only: %i[show edit update] do
    collection do
      get 'fab'
    end
  end

  resources :writers do
    collection do
      get 'show'
      get 'show_1'
      get 'show_2'
      get 'show_3'
      get 'show_4'
      get 'show_5'
      get 'show_6'
    end
  end

  namespace :api do
    resources :messages, only: :index, defaults: { format: 'json' }
  end
end

app/models/person.rb
class Person < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  mount_uploader :icon, ImageUploader
  validates :name, presence: true, uniqueness: true
  has_many :topics
  has_many :likes, dependent: :destroy

  def already_liked?(topic)
    likes.exists?(topic_id: topic.id)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def show
    @topic = Topic.find_by(id: params[:id])
    person = Person.find(params[:id])
    @person = Person.name
    @topics = person.topics.order("created_at DESC").limit(10)
    @icon = person.icon
    @person = Person.find_by(id: params[:id])
    @name = person.name
    @introduction = person.introduction
    # @topics = Topic.where(person_id: @parson)
    # @person = Person.find(current_person.id)
  end

  def fab
    @person = Person.find(current_person.id)
    @icon = @person.icon
    person = Person.find(current_person.id)
    @name = person.name
    @introduction = person.introduction
    @topics = Topic.all
    @like = Like.where(person_id: current_person.id)
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    if current_person.update(person_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def person_params
    params.require(:person).permit(:name, :email, :introduction, :icon, :password, :password_confirmation, :introduce, :image)
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_introduction.html.haml
.IntroTemple
  .UserInfo
    .UserInfo__icon
      - if @person.icon?
        = image_tag @icon.url, class: 'UserInfo__icon'
    .UserInfo__name
      = @name
    .UserInfo__Text
      = @introduction
      .UserInfo__contents
  .Posts
    -# = link_to "/people/#{current_person.id}"
    .PostsIndex
    = link_to "/people/#{current_person.id}", class: "post-index" do
      投稿一覧
    = link_to new_topic_path do
      新規投稿
    = link_to fab_people_path, class: "fab-index" do
      お気に入り

app/views/people/edit.html.haml
.Top
  = form_with local: true do |f|
    .Header
      .Title
        = link_to root_path, class: "title" do
          %h1 archi log
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", destroy_person_session_path, method: :delete, class: 'Button'
    = link_to "トップページに戻る", root_path, class: 'Button'
  .AccountPage__form
    = form_for(current_person) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      .FormField
        = f.label :icon, class: 'ProfIcon' do
          = icon('fas', 'user', class: 'icon')
          = f.file_field :icon, class: 'file'
      .FormField
        .FormField__label--normal
          = f.label :introduction
        .FormField__input--normal
          = f.text_area :introduction

      = f.submit "Update", class: 'Button UserButton'

app/views/people/fab.html.haml
%header
= render "main/header"
.Fab
  .FabSection
    = render "introduction"
    .FabSection
      .Section_Box
      - @topics.each do |topic|
        - if person_signed_in? && topic.liked_by?(current_person)
          .PickUp__ProjectBox
            = link_to topic_path(topic.id) do
              = image_tag topic.image.url, class: "PickUp-Pic"
            .PickUp__Text
              = link_to topic_path(topic.id), class: "PickUp" do
                = topic.title
              .PickUp__Text__Letter
                = topic.heading
              .PickUp__Text__Writer
                = topic.person.name


  .RightSide
    = render "main/recommended"

%footer
= render "main/footer"

app/views/people/show.html.haml
%header
= render "main/header"
.Fab
  - if current_person.try(:id) == @person.id
    .FabSection
      = render "introduction"
      .ProfSection
        .ProfSectionBox
        - @topics.each do |topic|
          .PickUp__ProjectBox
            = link_to topic_path(topic.id) do
              = image_tag topic.image.url, class: "PickUp-Pic"
            .PickUp__Text
              = link_to topic_path(topic.id), class: "PickUp" do
                = topic.title
              .PickUp__Text__Letter
                = topic.heading
              .PickUp__Text__Writer
                = topic.person.name
              .SubItems
                .SubItems__edit
                  = link_to '編集', edit_topic_path(topic.id), method: :get
                .SubItems__detail
                  = link_to '詳細', topic_path(topic.id), method: :get
                .SubItems__delete
                  = link_to '削除', topic_path(topic.id), method: :delete, data: {confirm: "本当に削除しますか?"}

  - else
    .Section
      .Section_Box
        .UserInfo
          .UserInfo__icon
            - if @person.icon?
              = image_tag @person.icon.url, class: 'UserInfo__icon'
          .UserInfo__name
            = @person.name
          .UserInfo__Text
            = @person.introduction
        .Posts
          .PostsIndex
            = "このライターの記事一覧(#{@topics.count}件)"
        - @topics.each do |topic|
          .PickUp__ProjectBox
            = link_to topic_path(topic.id) do
              = image_tag topic.image.url, class: "PickUp-Pic"
              .PickUp__Text
              = link_to topic_path(topic.id), class: "PickUp" do
                = topic.title
                .PickUp__Text__Letter
                  = topic.heading
                .PickUp__Text__Writer
                  = @person.name

  .RightSide
    = render "main/recommended"

%footer
= render "main/footer"