config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'
  devise_for :people
  devise_scope :person do
    post '/guest', to: 'guest_sessions#new_guest'
  end

  resources :topics do
    resource :likes, only: %i[create destroy]
    collection do
      get 'list_1'
      get 'list_2'
      get 'list_3'
      get 'list_4'
      get 'list_5'
      get 'list_6'
      get 'list_7'
      get 'index_1'
      get 'search'
    end
  end

  resources :people, only: %i[show edit update] do
    collection do
      get 'fab'
    end
  end

  resources :writers do
    collection do
      get 'show'
      get 'show_1'
      get 'show_2'
      get 'show_3'
      get 'show_4'
      get 'show_5'
      get 'show_6'
    end
  end

  namespace :api do
    resources :messages, only: :index, defaults: { format: 'json' }
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :image, presence: true
  validates :title, presence: true, length: { maximum: 30 }
  validates :heading, presence: true, length: { maximum: 140 }
  validates :description, presence: true
  mount_uploader :image, ImageUploader

  belongs_to :person, optional: true
  has_many :likes, dependent: :destroy
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  def self.search(search)
    if search != ""
      Topic.where('title LIKE(?) OR heading LIKE(?) OR description LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%")
    else
      Topic.all
    end
  end

  def liked_by?(person)
    likes.where(person_id: person.id).exists?
  end

  def save_tag(sent_tags)
    current_tags = tags.pluck(:tag_name) unless tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[edit update destroy]

  def index
    @tag_list = Tag.all
    @topics = Topic.all
    @topic = current_person.topics.new
  end

  def new
    @topic = Topic.new
    @person = Person.find(current_person.id)
    @icon = @person.icon
  end

  def create
    # @person = Person.find(current_person.id)
    # @icon = @person.icon
    @topic = Topic.new(topic_params)
    # tag_list = params[:topic][:tag_name].split(nil)
    if @topic.save
      # @topic.save_tag(tag_list)
      flash[:notice] = "記事が投稿されました"
      redirect_to topic_path(@topic)
    else
      render 'new'
    end
  end

  def edit
    @topic = Topic.find(params[:id])
    @person = Person.find(current_person.id)
    @icon = @person.icon
  end

  def update
    # @topic = Topic.find(params[:id])
    if @topic.update(topic_params)
      flash[:notice] = "記事が更新されました"
      redirect_to topic_path(@topic)
    else
      flash[:notice] = "記事の更新ができませんでした"
      render 'edit'
    end
  end

  def search
    @topics = Topic.search(params[:keyword])
    @person = Person.find(current_person.id)
    @icon = @person.icon
    # @topics =  Topic.all
  end

  def destroy
    # @topic = Topic.find(params[:id])
    @topic.destroy
    flash[:notice] = "記事が削除されました"
    redirect_to person_path(current_person.id)
  end

  def show
    @topic = Topic.find_by(id: params[:id])
    @person = Person.find_by(id: @topic.person_id)
    @like_count = Like.where(topic_id: @topic.id).count
    @person = Person.find(current_person.id)
    @icon = @person.icon
    @topic = Topic.find(params[:id])
    @topic_tags = @topic.tags
  end

  def index_1
    @tag_list = Tag.all
    @topics = Topic.all
  end

  def list_1
    @person = Person.find(current_person.id)
    @icon = @person.icon
  end

  def list_2
    @person = Person.find(current_person.id)
    @icon = @person.icon
  end

  def list_3
    @person = Person.find(current_person.id)
    @icon = @person.icon
  end

  def list_4
    @person = Person.find(current_person.id)
    @icon = @person.icon
  end

  def list_5
    @person = Person.find(current_person.id)
    @icon = @person.icon
  end

  def list_6
    @person = Person.find(current_person.id)
    @icon = @person.icon
  end

  def list_7
    @person = Person.find(current_person.id)
    @icon = @person.icon
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :heading, :description, :image, tag_name: []).merge(person_id: current_person.id)
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end

  # def set_person
  #   @person = Person.find(params[:person_id])
  # end
end

app/views/topics/edit.html.haml
%header
= render('main/header')
.NewTopic
  .NewTopic__page
    記事の編集
  .NewTopic__form
    -# = form_for @topic do |f|
    = form_with(model: @topic, local: true) do |f|
      .FormBox
        トップ画を選んでください
        .ImageLogo
          = f.label :image, class: 'ImageLogo__image' do
            = icon('far', 'image', class: 'ImageLogo__icon')
            = f.file_field :image, class: 'file'
        .FormBox__label--normal
          = f.label :タイトル
        .FormBox__input--normal
          = f.text_field :title
        .FormBox__label--normal
          = f.label :見出し
        .FormBox__input--normal
          = f.text_area :heading
        .FormBox__label--normal
          = f.label :本文
        .FormBox__input--normal
          = f.text_area :description, rows: 10
      .action
        = f.submit '更新する'
      .return
        = link_to '戻る', :back

app/views/topics/index_1.html.haml
%h3 タグリスト
- @tag_list.each do |list|
  %span
    = link_to list.tag_name, tag_posts_path(tag_id: list.id)
    = "(#{list.posts.count})"
　
%hr/
　
%h3 投稿する
= form_with(model: @topic, url: topics_path, local: true) do |f|
  = f.text_area :content
  %br/
  = "スペースを入力することで複数のタグを付けることができます。"
  = "例：音楽 文芸 スポーツ"
  = f.text_field :tag_name
  %br/
  = f.submit
　
%hr/
　
%h3 投稿一覧
- @topics.each do |topic|
  -# = link_to topic.content, topic

app/views/topics/list_1.html.haml
%header
= render "main/header"
.Article
  .Detail
    .ConceptBox
      .ConceptBox__Fabo
        .ConceptBox__star
          = icon('fas', 'star')
          10　お気に入り
      .ConceptBox__Hedding
        .ConceptBox__Picture
        = image_tag "/assets/1.jpg", alt: "image", class: 'Concept-Pic'
        .ConceptBox__Title
          【東京】新国立競技場がついに竣工！
        .ConceptBox_Text
          新国立競技場は、「杜のスタジアム」と題し、”木”を取り入れた、周辺環境と調和するスタジアム。木材と鉄骨のハイブリッド構造の屋根となっており、高さを約47.4mと低く設定することで、水平なラインを強調した、圧迫感の少ないデザインを採用している。
          .TopicsBox__Fab-btn
            = link_to "#", class: "fab-btn" do
              ★お気に入りに追加

    .Details
      .Detail_Heading
        予算の問題や住民運動の果てに設計を手掛けたのは隈研吾建築都市設計事務所と大成建設のJV
      .Detail_Border
      .Detail_Picture
      = image_tag "/assets/14.jpg", alt: "image", class: 'Detail-Pic'
      .Detail_Text
        　隈研吾は、「高輪ゲートウェイ駅」や「新風館跡地」にできる新複合施設の建築も手掛け、過去には南青山「サニーヒルズ」などを設計した国内外でも活躍する建築家。
        %br/
        自身が10歳の時に、建築家・丹下健三の手掛けた以前の国立競技場を目にしたことが建築家を目指すきっかけとなったと話し、周辺地域にも学生時代から馴染みがあった。
      .Detail_Picture
      = image_tag "/assets/15.jpg", alt: "image", class: 'Detail-Pic2'
      .Detail_Text2
        バンクーバーに計画中の高層ビル
        %br/
        %br/

      .Detail_Heading
        関連するタグ
      .Detail_Border
      .Recommend_list
        = form_with local: true do |f|
          .Recommend_btn
            .btn
              = link_to '隈研吾', class: 'btn'
            .btn
              = link_to '東京', class: 'btn'
            .btn
              = link_to 'コンペ', class: 'btn'

  .RightSide
    .wrapper
    = render "writers/profile_1"
    = render "main/recommended"


%footer
= render "main/footer"

app/views/topics/list_2.html.haml
%header
= render "main/header"
.Article
  .Detail
    .ConceptBox
      .ConceptBox__Fabo
        .ConceptBox__star
          = icon('fas', 'star')
          9　お気に入り
      .ConceptBox__Hedding
        .ConceptBox__Picture
        = image_tag "/assets/2.jpg", alt: "image", class: 'Concept-Pic'
        .ConceptBox__Title
          【スペイン】本当に2026年に完成予定！？
        .ConceptBox_Text
          完成までには300年以上を要すると言われていたスペイン随一の絶景スポット「サグラダ・ファミリア」。そんなサグラダ・ファミリアが、驚異的な工期短縮を見込めているのは一体なぜなのか、2026年完成予定の世界遺産の謎に迫ります。
          .TopicsBox__Fab-btn
            = link_to "#", class: "fab-btn" do
              ★お気に入りに追加

    .Details
      .Detail_Heading
        驚異的な工期短縮はなぜ？
      .Detail_Border
      %br/
      .Detail_Text
        　着工から100年以上が経過しても今なお建設途中という、珍しい世界遺産「サグラダ・ファミリア」。
        %br/
        2005年にユネスコの世界遺産に登録されましたが、当然その当時サグラダ・ファミリアはまだまだ未完成。かろうじて完成している建物のみという、部分的な世界遺産登録は世界でも異例と話題になりました。
        %br/
        %br/
      .Detail_Picture
      = image_tag "/assets/17.jpg", alt: "image", class: 'List-Pic'
      .Detail_Text
      　ガウディ亡き後弟子たちがこしらえた数々の資料もスペイン内戦で焼失してしまうというアクシデントに見舞われ、常に手探り状態で建設を進めていくしかなかったようです。
      %br/
      %br/
      　みなさんの中には、自分が生きている間にサグラダ・ファミリアの完成を見ることはないのだろうなぁと、漠然と思っていた人も多いかもしれませんね。
      %br/
      %br/

      .Detail_Heading
        関連するタグ
      .Detail_Border
      .Recommend_list
        = form_with local: true do |f|
          .Recommend_btn
            .btn
              = link_to 'スペイン', class: 'btn'
            .btn
              = link_to 'サグラダ', class: 'btn'
            .btn
              = link_to 'ファミリア', class: 'btn'
            .btn
              = link_to 'ガウディ', class: 'btn'

  .RightSide
    .wrapper
    = render "writers/profile_2"
    = render "main/recommended"

%footer
= render "main/footer"

app/views/topics/list_3.html.haml
%header
= render "main/header"
.Article
  .Detail
    .ConceptBox
      .ConceptBox__Fabo
        .ConceptBox__star
          = icon('fas', 'star')
          5　お気に入り
      .ConceptBox__Hedding
        .ConceptBox__Picture
        = image_tag "/assets/8.jpg", alt: "image", class: 'Concept-Pic'
        .ConceptBox__Title
          台湾・新竹市の図書館コンペ、平田晃久チームが「知の峡谷」で最優秀に
        .ConceptBox_Text
          メインストリートからの見下ろし。道に対して大きく開いた部分がエントランス。街の文化ゾーンをつなぐグリーンベルトは反対側の道路へと続いている。
          .TopicsBox__Fab-btn
            = link_to "#", class: "fab-btn" do
              ★お気に入りに追加

    .Details
      .Detail_Border
      %br/
      .Detail_Text
        　台湾・新竹市の図書館設計コンペで、平田晃久建築設計事務所（東京・港）とシィーエン・クオ・アーキテクト・アンド・アソシエーツ（台湾・台北市）の2社によるJV（共同企業体）の案が最優秀に選ばれた。
        %br/
        　新竹市図書館の設計コンセプトは「知の峡谷（Knowledge Canyon）」。街の文化ゾーンをグリーンベルトでつなぐという都市計画を踏襲して、グリーンベルトの軸を強化する知の峡谷を提案した。
        
      = image_tag "/assets/18.jpg", alt: "image", class: 'List-Pic'
      .Detail_Text
      　2枚の壁を立て、その間に、峡谷のようなリーディングルームをつくる。様々な年齢層や民族、志向の異なる人々が1つに集まるリビングルームのような場所にする。本を読むためだけの図書館を「小さな図書館（Small Library）」とするなら、この図書館は本に触発された様々なコミュニケーションの場が融合する「大きな図書館（Big Library）」を目指している。
      %br/
      %br/
      = image_tag "/assets/19.jpg", alt: "image", class: 'List-Pic'
      .Detail_Text2
        書架が一望できる「峡谷」の空間
        %br/
        %br/

      .Detail_Heading
        関連するタグ
      .Detail_Border
      .Recommend_list
        = form_with local: true do |f|
          .Recommend_btn
            .btn
              = link_to '平田晃久', class: 'btn'
            .btn
              = link_to '台湾', class: 'btn'
            .btn
              = link_to 'コンペ', class: 'btn'
            .btn
              = link_to '図書館', class: 'btn'

  .RightSide
    .wrapper
    = render "writers/profile_3"
    = render "main/recommended"

%footer
= render "main/footer"

app/views/topics/list_4.html.haml
%header
= render "main/header"
.Article
  .Detail
    .ConceptBox
      .ConceptBox__Fabo
        .ConceptBox__star
          = icon('fas', 'star')
          6　お気に入り
      .ConceptBox__Hedding
        .ConceptBox__Picture
        = image_tag "/assets/9.jpg", alt: "image", class: 'Concept-Pic'
        .ConceptBox__Title
          在来軸組みのカワグチテイJV案に、徳島県「awaもくよんプロジェクト」
        .ConceptBox_Text
          周辺への圧迫感を抑えるように2棟に分け、建物を敷地中央にコンパクトにまとめて、敷地内に分節されたオープンスペースをつくる。中庭に緩やかな掘り込みのスロープを設け、東西通り抜けの通路とする。
          .TopicsBox__Fab-btn
            = link_to "#", class: "fab-btn" do
              ★お気に入りに追加

    .Details
      .Detail_Border
      %br/
      .Detail_Text
        　徳島県は、県営住宅の整備事業「awaもくよんプロジェクト」の設計コンペで、最優秀作品に内野設計（徳島市）と島津臣志建築設計事務所（徳島県佐那河内村）、カワグチテイ建築計画（東京・杉並）の3社JV（共同企業体）による提案「軸組もくよんが紡ぐ、重なり合う営みと風景」を選んだ。優秀作品はビーツーエーアーキテクツ（東京・千代田）と松村建築計画研究所（徳島県鳴門市）、KAP（東京・千代田）の3社JVによる「積層木板の暮らし～これからの徳島をつくる県営住宅～」だった。
        %br/
        %br/
      .Detail_Text
      　「awaもくよんプロジェクト」は、県営住宅の建て替えと周辺空き地を活用した施設整備を対象とする事業だ。コンペでは、全国初となる4階建てで木造現しによる準耐火構造を設計条件として求めた。4階建ての木造現しは、2019年6月施行の改正建築基準法で可能になった。Library）」とするなら、この図書館は本に触発された様々なコミュニケーションの場が融合する「大きな図書館（Big Library）」を目指している。
      %br/
      %br/
      = image_tag "/assets/20.jpg", alt: "image", class: 'List-Pic'
      .Detail_Text2
        切妻屋根で木質化された北東側イメージ
        %br/
        %br/

      .Detail_Heading
        関連するタグ
      .Detail_Border
      .Recommend_list
        = form_with local: true do |f|
          .Recommend_btn
            .btn
              = link_to '徳島県', class: 'btn'
            .btn
              = link_to '島津臣志', class: 'btn'
            .btn
              = link_to '内野設計', class: 'btn'
            .btn
              = link_to 'カワグチテイ', class: 'btn'
            .btn
              = link_to 'コンペ', class: 'btn'

  .RightSide
    .wrapper
    = render "writers/profile_4"
    = render "main/recommended"

%footer
= render "main/footer"

app/views/topics/list_5.html.haml
%header
= render "main/header"
.Article
  .Detail
    .ConceptBox
      .ConceptBox__Fabo
        .ConceptBox__star
          = icon('fas', 'star')
          3　お気に入り
      .ConceptBox__Hedding
        .ConceptBox__Picture
        = image_tag "/assets/10.jpg", alt: "image", class: 'Concept-Pic'
        .ConceptBox__Title
          宮川清志 / SESNによる、美容クリニック「Men’s Clara」
        .ConceptBox_Text
          宮川清志 / SESNが設計した、東京・港区南青山の、美容クリニック「Men’s Clara」です。
          .TopicsBox__Fab-btn
            = link_to "#", class: "fab-btn" do
              ★お気に入りに追加

    .Details
      .Detail_Border
      %br/
      .Detail_Picture
        = image_tag "/assets/21.jpg", alt: "image", class: 'List-Pic'
      .Detail_Text
        港区南青山にある美容クリニック、Men’s Claraのクリニックデザイン。
        %br/
        %br/
      .Detail_Text
        3階建ての建築の特色を生かし、CASA、架空の邸宅というコンセプトをたて、ストーリー性のある体感ができる空間としています。
        %br/
        %br/
      .Detail_Text
        B１Fでは建具や面をスケールアウトさせ、1Fは部屋や壁ではなく柱を作り、2Fは扉や動線ではなく窓や街路を作り、主体をすり替えながら強調する事で、記憶の中の感覚知を行き来する事で架空の邸宅、CASAを架空性を保ったまま表現しています。
        %br/
        %br/

      .Detail_Heading
        関連するタグ
      .Detail_Border
      .Recommend_list
        = form_with local: true do |f|
          .Recommend_btn
            .btn
              = link_to '東京都', class: 'btn'
            .btn
              = link_to '南青山', class: 'btn'
            .btn
              = link_to '宮川清志', class: 'btn'
            .btn
              = link_to 'SESN', class: 'btn'

  .RightSide
    .wrapper
    = render "writers/profile_1"
    = render "main/recommended"

%footer
= render "main/footer"

app/views/topics/list_6.html.haml
%header
= render "main/header"
.Article
  .Detail
    .ConceptBox
      .ConceptBox__Fabo
        .ConceptBox__star
          = icon('fas', 'star')
          2　お気に入り
      .ConceptBox__Hedding
        .ConceptBox__Picture
        = image_tag "/assets/11.jpg", alt: "image", class: 'Concept-Pic'
        .ConceptBox__Title
          ザハ事務所など抑えて日建設計が当選、ロシア最大手銀行のTODコンペ
        .ConceptBox_Text
          中央に見える緩く弧を描いた建物が「ズベルバンク・シティー」。手前にモスクワ川が流れる。間口最大30mの細長い敷地となっている。
          .TopicsBox__Fab-btn
            = link_to "#", class: "fab-btn" do
              ★お気に入りに追加

    .Details
      .Detail_Border
      %br/
      .Detail_Text
        　ロシア・モスクワに建設するホールを核としたTOD（公共交通指向型開発）の国際指名設計コンペで、日建設計の案が最優秀に選ばれた。
        %br/
        %br/
      .Detail_Text
      　この設計コンペはロシア最大手の銀行、ズベルバンク（ロシア連邦貯蓄銀行）が主催。2019年8月20日に行われたプレゼンテーションには日建設計のほか、ザハ・ハディド・アーキテクツ（英国）やコープ・ヒンメルブラウ（オーストリア）、アルケア・アッソチャーティ（イタリア）の計4者が参加し、日建設計が当選した。
      %br/
      %br/
      = image_tag "/assets/22.jpg", alt: "image", class: 'List-Pic'
      .Detail_Text2
        長手方向の断面パース
      %br/
      %br/
      .Detail_Text
      　モスクワでのプレゼンテーションに参加した日建設計の亀井忠夫社長は、コンペ案について次のように語る。「チャレンジングではあるが、実現可能な案だ。外観は控えめな造形でありながらも、タイムレスなデザインで、内部空間が豊か。当社がインハウスエンジニアを多数抱えた総合設計事務所であることも評価された」
      %br/
      %br/
      = image_tag "/assets/23.jpg", alt: "image", class: 'List-Pic'
      .Detail_Text2
        南側から見るズベルバンク・シティー

      .Detail_Heading
        関連するタグ
      .Detail_Border
      .Recommend_list
        = form_with local: true do |f|
          .Recommend_btn
            .btn
              = link_to 'モスクワ', class: 'btn'
            .btn
              = link_to '日建設計', class: 'btn'
            .btn
              = link_to 'ロシア', class: 'btn'
            .btn
              = link_to 'コンペ', class: 'btn'

  .RightSide
    .wrapper
    = render "writers/profile_5"
    = render "main/recommended"

%footer
= render "main/footer"

app/views/topics/list_7.html.haml
%header
= render "main/header"
.Article
  .Detail
    .ConceptBox
      .ConceptBox__Fabo
        .ConceptBox__star
          = icon('fas', 'star')
          7　お気に入り
      .ConceptBox__Hedding
        .ConceptBox__Picture
        = image_tag "/assets/12.jpg", alt: "image", class: 'Concept-Pic'
        .ConceptBox__Title
          100者の応募を制したのはパーシモンヒルズ・アーキテクツ
        .ConceptBox_Text
          既存の民俗資料館（右手）と新しい公民館（中央上）、体育館（右下）によって囲まれた広場をつくり、町の顔とする。
          .TopicsBox__Fab-btn
            = link_to "#", class: "fab-btn" do
              ★お気に入りに追加

    .Details
      .Detail_Heading
        岩手県住田町の公民館プロポ
      .Detail_Border
      %br/
      .Detail_Text
        　岩手県住田町は、上有住（かみありす）地区公民館の設計者を選定する公募型プロポーザルで、最優秀賞にPERSIMMON HILLS architects（パーシモンヒルズ・アーキテクツ、川崎市）を選定した。優秀賞は喜多裕建築事務所（東京・文京）、福山弘構造デザイン（東京・港）、イー・エー・ユー（東京・文京）の3社による設計共同体だった。
        %br/
        %br/
        　パーシモンヒルズ・アーキテクツは、1986年生まれの柿木佑介氏と85年生まれの廣岡周平氏が、2016年に設立した。ともに関西大学工学部建築学科の出身（廣岡氏はその後、横浜国立大学大学院Y-GSA修了）。柿木氏はマウントフジアーキテクツスタジオ（東京・渋谷）、廣岡氏はSUEP.（スープ、東京・世田谷）と大成建設をそれぞれ経て、事務所を共同で立ち上げた。
        %br/
        %br/
        　プロポーザルには、120者から参加表明があり、100者から技術提案資料が提出された。9月13日に審査委員会による第1次審査が行われ、第2次審査対象者として、6者を選んだ。9月27日に公開プレゼンテーションと第2次審査会を実施し、提案課題である次の5項目についての考え方や実施方針などを評価のうえ、最優秀賞と優秀賞を選定した。
        %br/
        %br/
        （1）既存の民俗資料館との連続性、（2）建物の配置および外構計画、（3）地域産業の振興、（4）持続可能性の高い施設、（5）防災の要となる安全・安心な施設――。
        %br/
      .Detail_Picture
      = image_tag "/assets/24.jpg", alt: "image", class: 'Detail-Pic2'
      %br/
      %br/
      .Detail_Heading
        関連するタグ
      .Detail_Border
      .Recommend_list
        = form_with local: true do |f|
          .Recommend_btn
            .btn
              = link_to 'パーヒル', class: 'btn'
            .btn
              = link_to '岩手県', class: 'btn'
            .btn
              = link_to 'コンペ', class: 'btn'
            .btn
              = link_to '公民館', class: 'btn'

  .RightSide
    .wrapper
    = render "writers/profile_6"
    = render "main/recommended"

%footer
= render "main/footer"

app/views/topics/new.html.haml
%header
= render('main/header')
.NewTopic
  - if @topic.errors.any?
    .alert
      %h2= "#{@topic.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - @topic.errors.full_messages.each do |message|
          %li= message
  .NewTopic__page
    新規投稿
  .NewTopic__form
    = form_with(model: @topic, url: topics_path, local: true) do |f|
      .FormBox
        トップ画を選んでください
        .ImageLogo
          = f.label :image, class: 'ImageLogo__image' do
            = icon('far', 'image', class: 'ImageLogo__icon')
            = f.file_field :image, class: 'file'
        .FormBox__label--normal
          = f.label :タイトル
        .FormBox__input--normal
          = f.text_field :title, placeholder: "タイトルを入れてください(30文字以内)"
        .FormBox__label--normal
          = f.label :見出し
        .FormBox__input--normal
          = f.text_area :heading, placeholder: "見出しを入れてください(140文字以内)"
        .FormBox__label--normal
          = f.label :本文
        .FormBox__input--normal
          = f.text_area :description, rows: 10, placeholder: "本文を入れてください"
        = f.submit '投稿する'
      .return
        -# = link_to '戻る', :back

%footer
= render "main/footer"

app/views/topics/search.html.haml
%header
= render('main/header')
.Fab
  .Search
  = form_with(url: search_topics_path, local: true, method: :get, class: "search-form") do |f|
    - @topics.each do |topic|
      .PickUp__ProjectBox
        = link_to topic_path(topic.id) do
          = image_tag topic.image.url, class: "PickUp-Pic"
        .PickUp__Text
          = link_to topic_path(topic.id), class: "PickUp" do
            = topic.title
          .PickUp__Text__Letter
            = topic.heading
          .PickUp__Text__Writer
            = topic.person.name

  .RightSide
    = render "main/recommended"

%footer
= render "main/footer"

app/views/topics/show.html.haml
%header
= render "main/header"


.Topics
  .Detail
    .TopicsBox
      .ConceptBox__Fabo
        .ConceptBox__star
          = icon('fas', 'star')
          = @like_count
          お気に入り
      .TopicsBox__Hedding
        .TopicsBox__Picture
          = image_tag (@topic.image_url), class: 'Topics-Pic'
        .TopicsSec
          .TopicsBox__Title
            = @topic.title
          .TopicsBox_Text
            = @topic.heading
            .Favorite
            - if current_person.already_liked?(@topic)
              .Fav-btn
                = link_to "お気に入りを取り消す", topic_likes_path(@topic), method: :delete, class: 'fav-btn', remote: true
            - else
              .Fav-btn
                = link_to "★お気に入りに追加", topic_likes_path(@topic), method: :post, class: 'fav-btn', remote: true

    .Text
      .Text_Detail
        %span
        = markdown(@topic.description).html_safe

    -# .Tags
    -#   .Tag
    -#     = @tag_list.each do |list|
    -#   %span
    -#     = link_to list.tag_name, tag_topics_path(tag_id: list.id)
    -#     = "(#{list.topics.count})"

    .Tags
      .Tag
    - @topic_tags.each do |tag|
      "タグ: "
    %span

      -# = link_to tag.tag_name, tag_topics_path(tag_id: tag.id)
      -# = "(#{tag.topics.count})"

      .Detail_Heading
      -#   関連するタグ
      -# .Detail_Border
      .Recommend_list
        = form_with local: true do |f|
          .Recommend_btn


  .RightSide
    .wrapper
    = render "writers/profile"
    = render "main/recommended"

%footer
= render "main/footer"